title: בוריס גורליק
email: boris@gorelik.net
description: >- # this means to ignore newlines until "baseurl:"
  חוקר נתונים, מומחה להדמיית נתונים, מרצה
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title

blog_theme: light

paginate: 25
paginate_path: "/blog/page:num/"

social:
  youtube: hashavua
  spotify: hashavua

nav_pages:
  - name: Home
    url: /
  - name: My Blog in English
    url: "https://gorelik.net/blog"
  - name: השבוע במזרח התיכון
    url: /category/השבוע-במזרח-התיכון/
  - name: רעיון עבודה
    url: /category/רעיון-עבודה/
  - name: About Me
    url: "https://gorelik.net"

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
  my_categories:
    output: true
    permalink: /category/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: articles_by_category

plugins:
  - jekyll-feed
